Improve error handling of invalid options

diff --git a/pass-gen b/pass-gen
--- a/pass-gen
+++ b/pass-gen
@@ -14,7 +14,48 @@ NUMBER_OF_WORDS=6
 CAPITAL_COUNTER="$(( $(od -An -N2 -i /dev/urandom) % (2) ))" #randomly 1 or 2
 CAPITALIZATION_MODE="both"
 DISPLAY_PASSWORD=false
-#  CONFIG_FILE=~/.passgenrc
+
+
+#  If a configuration file exists, read values from it
+if [ -f /home/$USER/.passgenrc ]; then
+  echo "Reading preset values from ~/.passgenrc"
+  CONFIG_FILE="/home/$USER/.passgenrc"
+  ## Find the `current_project` key, and get the quoted string value 
+  if [ $(grep word-list $CONFIG_FILE) ]; then
+    WORDLIST=$(grep word-list $CONFIG_FILE | cut --delimiter== --fields=2)
+    WORDLIST=$(echo $WORDLIST | sed -e "s_~_/home/${USER}_")
+  fi
+  
+  if [ $(grep character-list $CONFIG_FILE) ]; then
+    CHARLIST=$(grep character-list $CONFIG_FILE | cut --delimiter== --fields=2)
+    CHARLIST=$(echo $CHARLIST | sed -e "s_~_/home/${USER}_")
+  fi
+
+  if [ $(grep capital-mode $CONFIG_FILE) ]; then
+    PADDING_LENGTH_BEFORE=$(grep capital-mode $CONFIG_FILE | cut --delimiter== --fields=2)
+  fi
+
+  if [ $(grep padding-before $CONFIG_FILE) ]; then
+    PADDING_LENGTH_BEFORE=$(grep padding-before $CONFIG_FILE | cut --delimiter== --fields=2)
+  fi
+  
+  if [ $(grep padding-after $CONFIG_FILE) ]; then
+    PADDING_LENGTH_AFTER=$(grep padding-after $CONFIG_FILE | cut --delimiter== --fields=2)
+  fi
+
+  if [ $(grep length $CONFIG_FILE) ]; then
+    NUMBER_OF_WORDS=$(grep length $CONFIG_FILE | cut --delimiter== --fields=2)
+  fi
+
+  if [ $(grep echo-password $CONFIG_FILE) ]; then
+    DISPLAY_PASSWORD=true
+  fi
+fi
+
+
+##
+## OPTION COMMANDS
+##
 
 cmd_version() {
   cat <<-_EOF
@@ -69,65 +110,74 @@ cmd_echo() {
   esac
 }
 
+cmd_length() {
+  case $1 in
+    ''|*[!0-9]*)             >&2 cat <<-_EOF 
+  "$1" is not a valid length.  
+  Please provide an integer number of words for the passphrase.
+	_EOF
+   exit 1;;
+    *)                       NUMBER_OF_WORDS=$1;;
+   esac
+}
 
-#  If a configuration file exists, read values from it
-if [ -f /home/$USER/.passgenrc ]; then
-  echo "Reading preset values from ~/.passgenrc"
-  CONFIG_FILE="/home/$USER/.passgenrc"
-  ## Find the `current_project` key, and get the quoted string value 
-  if [ $(grep word-list $CONFIG_FILE) ]; then
-    WORDLIST=$(grep word-list $CONFIG_FILE | cut --delimiter== --fields=2)
-    WORDLIST=$(echo $WORDLIST | sed -e "s_~_/home/${USER}_")
+cmd_wordlist() {
+  if [ ! -f $1 ]; then
+    echo "Wordlist file could not be found.  Does it exist?"
+    exit 1
+  elif [ ! -r $1 ]; then
+    echo "Wordlist file could not be opened.  Please ensure you have read permission."
+    exit 1
+  else
+    WORDLIST=$1
   fi
-  
-  if [ $(grep character-list $CONFIG_FILE) ]; then
-    CHARLIST=$(grep character-list $CONFIG_FILE | cut --delimiter== --fields=2)
-    CHARLIST=$(echo $CHARLIST | sed -e "s_~_/home/${USER}_")
-  fi
+}
 
-  if [ $(grep capital-mode $CONFIG_FILE) ]; then
-    PADDING_LENGTH_BEFORE=$(grep capital-mode $CONFIG_FILE | cut --delimiter== --fields=2)
+cmd_charlist() {
+  if [ ! -f $1 ]; then
+    echo "Character-list file could not be found.  Does it exist?"
+    exit 1
+  elif [ ! -r $1 ]; then
+    echo "Character-list file could not be opened.  Please ensure you have read permission."
+    exit 1
+  else
+    CHARLIST=$1
   fi
+}
 
-  if [ $(grep padding-before $CONFIG_FILE) ]; then
-    PADDING_LENGTH_BEFORE=$(grep padding-before $CONFIG_FILE | cut --delimiter== --fields=2)
-  fi
-  
-  if [ $(grep padding-after $CONFIG_FILE) ]; then
-    PADDING_LENGTH_AFTER=$(grep padding-after $CONFIG_FILE | cut --delimiter== --fields=2)
-  fi
+cmd_padding_length_before() {
+  case $1 in
+    ''|*[!0-9]*)             >&2 cat <<-_EOF 
+  "$1" is not a valid amount of padding.
+  Please provide a numerical value.
+	_EOF
+   exit 1;;
+    *)                       PADDING_LENGTH_BEFORE=$1;;
+   esac
+}
 
-  if [ $(grep length $CONFIG_FILE) ]; then
-    NUMBER_OF_WORDS=$(grep length $CONFIG_FILE | cut --delimiter== --fields=2)
-  fi
+cmd_padding_length_after() {
+  case $1 in
+    ''|*[!0-9]*)             >&2 cat <<-_EOF 
+  "$1" is not a valid amount of padding.
+  Please provide a numerical value.
+	_EOF
+   exit 1;;
+    *)                       PADDING_LENGTH_AFTER=$1;;
+   esac
+}
 
-  if [ $(grep echo-password $CONFIG_FILE) ]; then
-    DISPLAY_PASSWORD=true
-  fi
-fi
+cmd_capital_mode() {
+  case $1 in
+    all|initial|both)         CAPITALIZATION_MODE=$1;;
+    *)                        >&2 cat <<-_EOF 
+  "$1" is not a valid capitalization mode.
+  Please set the mode to 'all', 'initial', or 'both'.
+	_EOF
+   exit 1;;
+   esac
+}
 
-
-#  Process command-line options and update settings as required
-if [[ "$1" ]]; then     
-  while [[ "$1" ]]; do
-    currentParamater=$1
-    case "$1" in 
-      -l | --length) shift;                  NUMBER_OF_WORDS=$1; shift ;;
-      --word-list) shift;                    WORDLIST=$1; shift ;;
-      --special-character-list) shift;       CHARLIST=$1; shift ;;
-      --padding-before) shift;               PADDING_LENGTH_BEFORE=$1; shift ;;
-      --padding-after) shift;                PADDING_LENGTH_AFTER=$1; shift ;;
-      --capital-mode) shift;                 CAPITALIZATION_MODE=$1; shift ;;
-      -e | --echo-password) shift;           cmd_echo "$@";
-                                             if [[ $? == 0 ]]; then 
-                                               shift
-                                             fi ;;
-      -v | -V | --version) shift;            cmd_version ;;
-      -h | --help) shift;                    cmd_help ;;
-      *)                                     cmd_error "$@" ;;
-    esac
-  done
-fi
 
 
 #  Pick a random symbol from CHARLIST
@@ -218,6 +268,28 @@ clear_passphrase() {
   PADDING_AFTER=""
 }
 
+
+#  Process command-line options and update settings as required
+if [[ "$1" ]]; then     
+  while [[ "$1" ]]; do
+    currentParamater=$1
+    case "$1" in 
+      -l | --length) shift;                  cmd_length "$@"; shift ;;
+      --word-list) shift;                    cmd_wordlist "$@"; shift ;;
+      --special-character-list) shift;       cmd_charlist "$@"; shift ;;
+      --padding-before) shift;               cmd_padding_length_before "$@"; shift ;;
+      --padding-after) shift;                cmd_padding_length_after "$@"; shift ;;
+      --capital-mode) shift;                 cmd_capital_mode "$@"; shift ;;
+      -e | --echo-password) shift;           cmd_echo "$@";
+                                             if [[ $? == 0 ]]; then 
+                                               shift
+                                             fi ;;
+      -v | -V | --version) shift;            cmd_version ;;
+      -h | --help) shift;                    cmd_help ;;
+      *)                                     cmd_error "$@" ;;
+    esac
+  done
+fi
 generate_passphrase
 echo -n "$RANDOM_PASS" | xclip -selection "clipboard"
 >&2 echo "Generated passphrase copied to clipboard.  Will clear in 45 seconds."
